# -*- coding: utf-8 -*-
"""world-food-production.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g2QxUCI4_YFrRjCO8Pwv_uPHBSaAupgL

#  **World Food Production**

## Step 1| **Import Libraries**<a id="Step-1"></a>
"""

# Import libraries
import pandas as pd
import numpy as np

# Data visualization libraries
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

# Ignore warnings
import warnings
warnings.filterwarnings('ignore')

# Display maximum Rows and Columns
pd.set_option('display.max_columns', None)  # Allows Pandas to show all columns without limiting the number
pd.set_option('display.max_rows', None)     # Allows Pandas to show all rows without limiting the number

"""## Step 2| **Load the Dataset** <a id="Step-2"></a>"""

df = pd.read_csv('https://drive.google.com/uc?id=1UPZGVIo1VJLnTGwsHa5WNsz_VjGq3vFh')  # Load CSV file directly from Google Drive
df.head()       # Print first five rows

# Lets check the columns present in the Dataset
print(f"The number of columns present in the Dataset are:\n {df.columns}")

# Lets check the rows present in the Dataset
print(f"The number of rows in the Dataset is:\n {df.shape[0]}")

# Lets check the unique values present in the Data
df.nunique()

"""<!-- ## **Exploratory Data Analysis( EDA )** -->
<a id="eda"></a>
## <span style="font-weight: bold; color: Red; font-size: 35px;">Step 3| **Exploratory Data Analysis (EDA)**</span>

## Step 3.1| **Data Structure**<a id="Step-3.1"></a>
"""

# Lets check the Data Structure
df.info()

"""### `Observation:`
>* In this Dataset there is one column (Entity) which have object Datatype
>* Year column is of int Datatype
>* Other 22 columns have Float Datatype

## Step 3.2| **Data shape**<a id="Step-3.2"></a>
"""

# lets check the shape of Dataset
print(df.shape)

# print the number of Rows and Columns in Dataset
print("Number of rows in Dataset", df.shape[0])
print("Number of columns in Dataset:", df.shape[1])

"""<a id="missing-values"></a>
## <span style="font-weight: bold; color: Red; font-size: 35px;">Step 3.3| **Missing Values**</span>
"""

df.isnull().sum().sort_values(ascending=False)

print('There is no missing values present in Dataset')

"""## Step 3.4| **Lets Explore Each column**<a id="Step-3.4"></a>

### Step 3.4.1| **Lets Explore Entity column**<a id="Step-3.4.1"></a>
"""

entity_count = df['Entity'].nunique()
print("Number of entities:", entity_count)

# Count the occurrences of each entity name
entity_counts = df['Entity'].value_counts()

# Get the entity name with the maximum occurrence
max_entity= entity_counts.idxmax()
print("Entity with the maximum occurrence:", max_entity)

# Find the entity name with the minimum occurrence
min_entity = df['Entity'].value_counts().idxmin()
print("Entity with the minimum occurrence:", min_entity)

# Count the occurrences of each entity name
entity_counts = df['Entity'].value_counts()

# Get the top 5 entities with the maximum occurrence
max_entities = entity_counts.nlargest(5).index.tolist()

# Get the bottom 35 entities with the minimum occurrence
min_entities = entity_counts.nsmallest(5).index.tolist()

# Print the names of the entities with the maximum occurrence
print("Names of entities with the maximum occurrence:")
for entity in max_entities:
    print(entity)

# Print the names of the entities with the minimum occurrence
print("Names of entities with the minimum occurrence:")
for entity in min_entities:
    print(entity)

"""### Observations:
>* In this Dataset 226 Unique Entities are present
>* The 5 Entities which have Maximum occurance are: Afghanistan, Nicaragua, Morocco, Mozambique, Myanmar
>* The 5 Entities which have Minimum Occurance are: Finland, Ireland, Malta, Estonia, Sweden

### Step 3.4.2| **Lets Explore Year Column**<a id="Step-3.4.2"></a>
"""

#Lets Explore the year column
df['Year'].describe()

years = df['Year'].unique()

if years.size > 0:
    start_year = years.min()
    end_year = years.max()
    print("Starting year:", start_year)
    print("Last year:", end_year)
else:
    print("No data available.")

"""### `Observation:`
>* This Dataset is collected from the year 1961 until 2021 of different entities food production

#### Step 3.4.2.1| **Lets see the top producer of Each crop**<a id="Step-3.4.2.1"></a>
"""

# Filter the dataset for the most recent year
most_recent_year = df['Year'].max()
recent_year_df = df[df['Year'] == most_recent_year]
# Iterate through each crop column
for column in recent_year_df.columns:
    if column != 'Entity' and column != 'Year':
        # Find the country with the maximum production for the current crop
        top_country = recent_year_df.loc[recent_year_df[column].idxmax(), 'Entity']

        # Print the top producer for the current crop
        print(f"The top producer for {column} is {top_country}.")

"""### Step 3.4.3| **Lets Explore the Maize Production (tonnes) column**<a id="Step-3.4.3"></a>"""

# Lets Explore the Maize Production (tonnes) column
df['Maize Production (tonnes)'].describe()

sns.barplot(df, y='Maize Production (tonnes)')

fig=px.histogram(data_frame=df, x='Maize Production (tonnes)', color='Entity')
fig.show()

"""### `Observations:`
>* The Mean of Maize Production (tonnes) is 1.926434e+07
>* The Maximum Maize Production (tonnes) is 1.210235e+09
>* The Mainimum Maize Production (tonnes) is 0.000000e+00

### Step 3.4.4| **Lets Explore the Rice  Production ( tonnes) column**<a id="Step-3.4.4"></a>
"""

# Lets Explore the Rice  Production (tonnes) column
print('The Mode of Rice  Production ( tonnes) is:', df['Rice  Production ( tonnes)'].mode()[0])
print('The Mean of Rice  Production ( tonnes) is:',df['Rice  Production ( tonnes)'].mean())
print('The Median of Rice  Production ( tonnes) is:',df['Rice  Production ( tonnes)'].median())

# Filter the year 2021
df_1=df[df['Year']==2021]
# lets check the Rice Production(tonnes) in the year 2021 according to this Data
df_1.groupby('Year')['Rice  Production ( tonnes)'].sum()

# Lets Calculate the percentage of rice produced in year 2021
rice_production_2021=df_1['Rice  Production ( tonnes)'].sum()
Total_rice_production=df['Rice  Production ( tonnes)'].sum()
# Percentage of the Rice Production in the year 2021
percentage_of_rice_2021=(rice_production_2021)/(Total_rice_production)*100
# Print the percentage of Rice Produced in year 2021
print("The percentage of Rice produced in the Year 2021 is: ",round(percentage_of_rice_2021, 4))

# Filter the year 2021
df_1=df[df['Year']==2021]
# lets check the Rice Production(tonnes) in the year 2021 according to this Data
rice_production_2021=df_1.groupby('Entity')['Rice  Production ( tonnes)'].sum()
# Total rice production
total_rice_production_2021=rice_production_2021.sum()
# percentage of rice in year 2021
percentage_of_rice_2021=(rice_production_2021)/(total_rice_production_2021)*100
# print the percentage of rice produced by entity
print("The percentage of rice produced by each Entity in the Year 2021 is:", percentage_of_rice_2021)

fig=px.bar(df, x=percentage_of_rice_2021.index, y=percentage_of_rice_2021)
fig.update_layout(
    title='percentage_of_rice_2021',
    xaxis_title='Entity',
    yaxis_title='percentage (%)'
)
fig.show()

# Filter the year 1961
df_2=df[df['Year']==1961]
# lets check the Rice Production(tonnes) in the year 1961 according to this Data
df_2.groupby('Year')['Rice  Production ( tonnes)'].sum()

# Lets Calculate the percentage of rice produced in year 2021
rice_production_1961=df_2['Rice  Production ( tonnes)'].sum()
Total_rice_production=df['Rice  Production ( tonnes)'].sum()
# Percentage of the Rice Production in the year 2021
percentage_of_rice_1961=(rice_production_1961)/(Total_rice_production)*100
# Print the percentage of Rice Produced in year 2021
print("The percentage of Rice produced in the Year 1961 is: ",round(percentage_of_rice_1961, 4))

# Filter the year 1961
df_2 = df[df['Year'] == 1961]

# Calculate the rice production in the year 1961 for each entity
rice_production_1961 = df_2.groupby('Entity')['Rice  Production ( tonnes)'].sum()

# Calculate the total rice production in the year 1961
total_rice_production_1961 = rice_production_1961.sum()

# Calculate the percentage of rice produced in the year 1961 for each entity
percentage_of_rice_1961 = (rice_production_1961 / total_rice_production_1961) * 100

# Print the percentage of rice produced in the year 1961 for each entity
print("Percentage of Rice produced in the Year 1961 by Entity:")
print(percentage_of_rice_1961)

fig=px.bar(data_frame=df, x=percentage_of_rice_1961.index, y=percentage_of_rice_1961)
fig.update_layout(
    title="Percentage of Rice produced in the Year 1961 by Entity",
    xaxis_title="Entity",
    yaxis_title="Percentage (%)"
)

fig.show()

"""### `Observation:`
>* The percentage of Rice produced in the Year 1961 is:  1.6944
>* The percentage of Rice produced in the Year 2021 is:  2.1765  
  1. The Rice produced in the Year 2021 in greater percentage in America and Asia is: 11.8141
  2. The Rice produced in the Year 1961 in greater percentage in Asia and Asia(FAO) is: 15.56197
  3. The Maximum Rice production percentage in 1961 is of Armenia and Asia
  4. The Maximum Rice production percentage in 2021 is of Asia
"""

staple_crops = ['Maize Production (tonnes)', 'Rice  Production ( tonnes)', 'Wheat Production (tonnes)']
staple_data = df[['Year'] + staple_crops]
staple_data['Year'] = staple_data['Year'].astype(int)
grouped_data = staple_data.groupby('Year')[staple_crops].sum()
grouped_data.plot(kind='line')
plt.xlabel('Year')
plt.ylabel('Production (tonnes)')
plt.title('Production Evolution of Maize, Rice, and Wheat')
plt.legend()
plt.show()

"""`This Graph Indicates that the Maximum production is of Maize (tonnes) according to this Dataset`

### Step 3.4.5| **Lets Explore Yams  Production (tonnes) Column**<a id="Step-3.4.5"></a>
"""

df['Yams  Production (tonnes)'].describe()

total_yams_production=df['Yams  Production (tonnes)'].sum()
grouped_df=df.groupby('Year')['Yams  Production (tonnes)'].sum().reset_index()
first_year_production = grouped_df.iloc[0]
last_year_production = grouped_df.iloc[-1]
first_and_last_year_production_df = pd.DataFrame([first_year_production, last_year_production])
first_and_last_year_production_df

# Diffrence in Yams producion in 1961 and 2021
Yams_production_in_1961=4.177913e+08
Yams_production_in_2021=6.909884e+08
Yams_Difference=Yams_production_in_2021-Yams_production_in_1961
Yams_Difference

Yams_df=df[['Entity', 'Yams  Production (tonnes)']]
max_Yams_Entity=Yams_df.loc[Yams_df['Yams  Production (tonnes)'].idxmax(), 'Entity']
# print the country which produced maximum Yams
print("The country that produces maximum Yams is: ", max_Yams_Entity)

# Filter the year 1961
df_2 = df[df['Year'] == 1961]

# Calculate the yams production in the year 1961 for each entity
Yams_production_1961 = df_2.groupby('Entity')['Yams  Production (tonnes)'].sum()

# Calculate the total yams production in the year 1961
total_Yams_production_1961 = Yams_production_1961.sum()

# Calculate the percentage of yams produced in the year 1961 for each entity
percentage_of_Yams_1961 = (Yams_production_1961 / total_Yams_production_1961) * 100

# Print the percentage of yams produced in the year 1961 for each entity
print("Percentage of Yams produced in the Year 1961 by Entity:")
print(percentage_of_Yams_1961)

fig=px.bar(data_frame=df, x=percentage_of_Yams_1961.index, y=percentage_of_Yams_1961)
fig.update_layout(
    title="Percentage of Yams produced in the Year 1961 by Entity",
    xaxis_title="Entity",
    yaxis_title="Percentage (%)"
)

fig.show()

# Filter the year 2021
df_1 = df[df['Year'] == 2021]

# Calculate the yams production in the year 2021 for each entity
Yams_production_2021 = df_1.groupby('Entity')['Yams  Production (tonnes)'].sum()

# Calculate the total yams production in the year 2021
total_Yams_production_2021 = Yams_production_2021.sum()

# Calculate the percentage of yams produced in the year 2021 for each entity
percentage_of_Yams_2021 = (Yams_production_2021 / total_Yams_production_2021) * 100

# Print the percentage of yams produced in the year 1961 for each entity
print("Percentage of Yams produced in the Year 2021 by Entity:")
print(percentage_of_Yams_2021)

fig=px.bar(data_frame=df, x=percentage_of_Yams_2021.index, y=percentage_of_Yams_2021)
fig.update_layout(
    title="Percentage of Yams produced in the Year 2021 by Entity",
    xaxis_title="Entity",
    yaxis_title="Percentage (%)"
)

fig.show()

# Create an animation plot of the yams column
fig=px.scatter(df, y='Yams  Production (tonnes)', x='Year', color='Entity')
fig.show()

"""### `Observation:`
* The Maximum Yams produced Each year is 7.871405e+07
  1. The Mean of Yams produced Each year is 2.744973e+06
  2. In the Year 1961	the Yams produced is 4.177913e+08
  3. In the Year 2021 the Yams produced is 6.909884e+08
  4. `The Difference in the production of Yams in Year 1961 and 2021 is 273197100.0`
  5. The country that produces maximum Yams is:  `Jamaica`
  6. The Maximum Yams production percentage in 1961 is of vitenam
  7. The Maximum Yams Production Percentage in 2021 is of Switzerland

### Step 3.4.6| **Lets Explore The Wheat Production(tonnes) column**<a id="Step-3.4.6"></a>
"""

df['Wheat Production (tonnes)'].describe()

# Filter the year 1961
df_2=df[df['Year']==1961]
# lets check the Rice Production(tonnes) in the year 1961 according to this Data
df_2.groupby('Year')['Wheat Production (tonnes)'].sum()

# Lets Calculate the percentage of rice produced in year 2021
Wheat_Production_1961=df_2['Wheat Production (tonnes)'].sum()
Total_Wheat_Production_1961=df['Wheat Production (tonnes)'].sum()
# Percentage of the Rice Production in the year 2021
percentage_of_Wheat_1961=(Wheat_Production_1961)/(Total_Wheat_Production_1961)*100
# Print the percentage of Rice Produced in year 2021
print("The percentage of Wheat produced in the Year 1961 is: ",round(percentage_of_Wheat_1961, 4))

# Filter the dataset for wheat production
wheat_df = df[['Entity', 'Wheat Production (tonnes)']]

# Find the country with maximum wheat production
max_wheat_country = wheat_df.loc[wheat_df['Wheat Production (tonnes)'].idxmax(), 'Entity']

print("Country with maximum wheat production:", max_wheat_country)

# Filter the year 2021
df_2 = df[df['Year'] == 1961]

# Calculate the yams production in the year 2021 for each entity
Wheat_production_1961 = df_2.groupby('Entity')['Wheat Production (tonnes)'].sum()

# Calculate the total yams production in the year 2021
total_Wheat_production_1961 = Wheat_production_1961.sum()

# Calculate the percentage of yams produced in the year 2021 for each entity
percentage_of_Wheat_1961 = (Wheat_production_1961 / total_Wheat_production_1961) * 100

# Print the percentage of yams produced in the year 1961 for each entity
print("Percentage of Wheat produced in the Year 1961 by Entity:")
print(percentage_of_Wheat_1961)

fig = px.bar(data_frame=df, x='Entity', y='Wheat Production (tonnes)', color='Year',
             labels={'Wheat Production (tonnes)': 'Wheat Production (tonnes)'},
             title="Wheat Production by Entity")

fig.update_layout(xaxis_title="Entity", yaxis_title="Wheat Production (tonnes)")
fig.show()

fig=px.scatter(df, y='Wheat Production (tonnes)', x='Year', color='Entity')
fig.show()

"""### `Observations:`
* The Maximum production of Wheat is 7.723055e+08
* The mean of Wheat produced is  2.365684e+07
* The percentage of Wheat produced in the Year 1961 in jamaica is:  1.4567
* Country with maximum wheat production: `Saint Lucia`

### Step 3.4.7| **Lets Explore the Tomatoes Production (tonnes) column**<a id="Step-3.4.7"></a>
"""

# Summary Statistics of omatoes Production (tonnes) column
df['Tomatoes Production (tonnes)'].describe()

max_tomatoes_row = df.loc[df['Tomatoes Production (tonnes)'].idxmax()]
max_tomatoes_year = max_tomatoes_row['Year']
max_tomatoes_country = max_tomatoes_row['Entity']

print("The year and country with the maximum tomatoes production are:", max_tomatoes_year, "in", max_tomatoes_country)

# lets check the tomatoes production in year
Tomatoes_df = df[['Tomatoes Production (tonnes)', 'Year', 'Entity']]
max_tomatoes_Entity = Tomatoes_df.loc[Tomatoes_df['Tomatoes Production (tonnes)'].idxmax(), 'Entity']
print("The Entity with max Tomatoes production is:", max_tomatoes_Entity)

# Lets check the production of tomatoes in year 1963
df_3=df[df['Year']==1963]
tomatoes_production_1963=df_3['Tomatoes Production (tonnes)'].sum()
total_tomatoes_production_1963=df['Tomatoes Production (tonnes)'].sum()
tomatoes_percentage_1963=tomatoes_production_1963/total_tomatoes_production_1963*100
# print the tomatoes produced in year 1963
print("The total Tomatoes Production in 1963 is: ",tomatoes_percentage_1963)

fig = px.bar(data_frame=df, x='Entity', y='Tomatoes Production (tonnes)', color='Year',
             labels={'Tomatoes Production (tonnes)': 'Tomatoes Production (tonnes)'},
             title="Tomatoes Production by Entity")
fig.update_layout(xaxis_title="Entity", yaxis_title="Tomatoes Production (tonnes)")
fig.show()

"""### `Observations: `
* In the Year 1963 the maximum Tomatoes are produced
* The country which produced Maximum Tomatoes is `Western Asia (FAO)`
* The total Tomatoes Production percentage in 1963 is: 2.1447850906250134
* The maximum Tomatoes production is 1.891340e+08

### Step 3.4.8| **Lets Explore the Tea  Production ( tonnes ) column**<a id="Step-3.4.8"></a>
"""

df['Tea  Production ( tonnes )'].describe()

# Lets check the Entity and year in which maximum Tea is produced
max_tea_row=df.loc[df['Tea  Production ( tonnes )'].idxmax()]
max_tea_year=max_tea_row['Year']
max_tea_Entity=max_tea_row['Entity']
# print the Entity and year in which maximum tea production takes place
print("The entity and year in which maximum tea was produced is: ", max_tea_year, 'in', max_tea_Entity)

df_4=df[df['Year']==2018]
# calculate the percentage of tea produced in year 2018
tea_production_2018=df_4['Tea  Production ( tonnes )'].sum()
total_tea_production=df['Tea  Production ( tonnes )'].sum()
# percentage of tea produced in 2018
percentage_of_tea_produced_in_2018=(tea_production_2018/total_tea_production)*100
# print the percentage of tea produced in 2018
print("The percentage of Tea Produced in the Year 2018 is: ",percentage_of_tea_produced_in_2018)

# Data
labels = ['Tea Produced in 2018', 'Tea Produced in Other Years']
sizes = [percentage_of_tea_produced_in_2018, 100 - percentage_of_tea_produced_in_2018]
colors = ['#ff9999','#66b3ff']
explode = (0.1, 0)  # Explode the first slice (Tea Produced in 2018)

# Plot
plt.pie(sizes, explode=explode, labels=labels, colors=colors, autopct='%1.1f%%', startangle=90)

# Aspect ratio ensures that pie is drawn as a circle
plt.axis('equal')

# Title
plt.title('Percentage of Tea Production in 2018')

# Display the chart
plt.show()

sns.histplot(df['Tea  Production ( tonnes )'])

"""## `Observation:`
* The year in which maximum tea was produced is:  `2018`
* The entity in which maximum tea was produced is: `Chad`
* The percentage of Tea Produced in the Year 2018 is:  2.1649562305300463 i-e about 2.2

### Step 3.4.9| **Lets Explore the Sweet potatoes  Production (tonnes)**<a id="Step-3.4.9"></a>
"""

df['Sweet potatoes  Production (tonnes)'].describe()

# Lets check the Entity and year in which maximum Tea is produced
max_potato_row=df.loc[df['Sweet potatoes  Production (tonnes)'].idxmax()]
max_potato_year=max_potato_row['Year']
max_potato_Entity=max_potato_row['Entity']
# print the Entity and year in which maximum tea production takes place
print("The entity and year in which maximum Sweet potatoes was produced is: ", max_potato_year, 'in', max_potato_Entity)

df_5=df[df['Year']==1994]
# calculate the percentage of tea produced in year 2018
potato_production_1994=df_4['Sweet potatoes  Production (tonnes)'].sum()
total_potato_production=df['Sweet potatoes  Production (tonnes)'].sum()
# percentage of tea produced in 2018
percentage_of_potato_produced_in_1994=(potato_production_1994/total_tea_production)*100
# print the percentage of tea produced in 2018
print("The percentage of Sweet potato Produced in the Year 1994 is: ",percentage_of_potato_produced_in_1994)

# Data
labels = ['potato produced in 1994', 'potato Produced in Other Years']
sizes = [percentage_of_potato_produced_in_1994, 100 - percentage_of_potato_produced_in_1994]
colors = ['#ff9999','#66b3ff']
explode = (0.1, 0)  # Explode the first slice (Tea Produced in 2018)

# Plot
plt.pie(sizes, explode=explode, labels=labels, colors=colors, autopct='%1.1f%%', startangle=90)

# Aspect ratio ensures that pie is drawn as a circle
plt.axis('equal')

# Title
plt.title('Percentage of potato Production in 1994')

# Display the chart
plt.show()

"""### `Observations:`
* The year in which maximum Sweet potatoes was produced is: `1994`
* The entity in which maximum Sweet potatoes was produced is: `Rwanda`
  * The percentage of Sweet potato Produced in the Year 1994 in Rwanda is: 68.34715521906779
  * The Maximum Sweet potato production is 1.528620e+08
  * The percentage of Sweet potato Produced in the Year 1996 is:  19.685235790382947
  * By  pie chart it is predicted That The percentage of potato produced in 1994 is Greater than the Other years

### Step 3.4.10| **Lets Explore the Sunflower seed  Production (tonnes) column**<a id="Step-3.4.10"></a>
"""

df['Sunflower seed  Production (tonnes)'].describe()

# Lets check the Entity and year in which maximum Tea is produced
max_Sunflower_row=df.loc[df['Sunflower seed  Production (tonnes)'].idxmax()]
max_Sunflower_year=max_Sunflower_row['Year']
max_Sunflower_Entity=max_Sunflower_row['Entity']
# print the Entity and year in which maximum tea production takes place
print("The entity and year in which maximum sunflower was produced is: ", max_Sunflower_year, 'in', max_Sunflower_Entity)

df_5=df[df['Year']==1996]
# calculate the percentage of tea produced in year 2018
Sunflower_production_1996=df_5['Sunflower seed  Production (tonnes)'].sum()
total_Sunflower_production=df['Sunflower seed  Production (tonnes)'].sum()
# percentage of tea produced in 2018
percentage_of_Sunflower_produced_in_1996=(Sunflower_production_1996/total_tea_production)*100
# print the percentage of tea produced in 2018
print("The percentage of Sunflower Produced in the Year 1996 is: ",percentage_of_Sunflower_produced_in_1996)

import plotly.express as px

fig = px.bar(data_frame=df, x='Entity', y='Sunflower seed  Production (tonnes)', color='Year',
             labels={'Sunflower seed  Production (tonnes)': 'Sunflower seed  Production (tonnes)'},
             title="Sunflower Production by Entity")

fig.update_layout(xaxis_title="Entity", yaxis_title="Sunflower Production (tonnes)")
fig.show()

fig=px.scatter(df, y='Sunflower seed  Production (tonnes)', x='Year',
               color='Entity')
fig.show()

"""### `Observations:`
>* The entity in which maximum Sunflower was produced is:`Least Developed Countries (FAO)`
>* The year in which maximum Sunflower was produced in Least Developed Countries (FAO) is: `1996`
>* The maximum Sunflower percentage is 5.818563e+07
>* The percentage of Sunflower Produced in the Year 1996 is:  19.685235790382947

### Step 3.4.11| **Lets Explore the Sugar cane Production (tonnes) column**<a id="Step-3.4.11"></a>
"""

df['Sugar cane Production (tonnes)'].describe()

df_6=df[df['Year']==1997]
df_6.groupby('Year')['Sugar cane Production (tonnes)'].sum()

# Lets check the Entity and year in which maximum Tea is produced
max_Sugarcane_row=df.loc[df['Sugar cane Production (tonnes)'].idxmax()]
max_Sugarcane_year=max_Sugarcane_row['Year']
max_Sugarcane_Entity=max_Sugarcane_row['Entity']
# print the Entity and year in which maximum tea production takes place
print("The entity and year in which maximum Sugarcane was produced is: ", max_Sugarcane_year, 'in', max_Sugarcane_Entity)

df_6=df[df['Year']==1997]
# calculate the percentage of tea produced in year 2018
Sugarcane_production_1997=df_6['Sugar cane Production (tonnes)'].sum()
total_Sugarcane_production=df['Sugar cane Production (tonnes)'].sum()
# percentage of tea produced in 2018
percentage_of_Sugarcane_produced_in_1997=(Sugarcane_production_1997/total_Sugarcane_production)*100
# print the percentage of tea produced in 2018
print("The percentage of Sugarcane Produced in the Year 1997 is: ",percentage_of_Sugarcane_produced_in_1997)

"""### `Observations:`
>* The entity in which maximum Sugarcane was produced is: `Peru`
  >* The year in which maximum Sugarcane was produced in peru is: `1997`
  >* The percentage of Sugarcane Produced in the Year 1997 is:  1.8481278570035378
  >* The maximum production percentage of Sugarcane is 1.958234e+09

### Step 3.4.12| **Lets Explore the Soybeans  Production (tonnes)**<a id="Step-3.4.12"></a>
"""

df['Soybeans  Production (tonnes)'].describe()

# Lets check the Entity and Year in which maximum soya bean (tonnes) is produced
soyabean_df=df.loc[df['Soybeans  Production (tonnes)'].idxmax()]
soyabean_Entity=soyabean_df['Entity']
soyabean_Year=soyabean_df['Year']
# print the Entity and year in which maximum tea production takes place
print("The entity and year in which maximum Soya Beans production took place are:", soyabean_Entity, 'in', soyabean_Year)

# Filter the year 2009
df_7=df[df['Year']==2009]
# calculate the soyabean production in year 2018
soya_production =df_7['Soybeans  Production (tonnes)'].sum()
# calculate the Total percentage
total_soya_production= df['Soybeans  Production (tonnes)'].sum()
# percentage of soyabean
percentage_of_soyabean_produced_in_2009=(soya_production/total_soya_production)*100
# print the soyabean production percentage in 2009
print("The percentage of Soyabeans produced in 2009 is", percentage_of_soyabean_produced_in_2009)

# Difference in percentage between soyabean and sunflower
percentage_Difference_sunflower_and_soyabean=percentage_of_Sunflower_produced_in_1996-percentage_of_soyabean_produced_in_2009
percentage_Difference_sunflower_and_soyabean

percentage_soybean_2009 = 2.3029780766186674  # specify the percentage of soybean produced in 2009
percentage_sunflower_1996 = 19.685235790382947  # specify the percentage of sunflower produced in 1996

difference = percentage_sunflower_1996 - percentage_soybean_2009

# Create a pie chart
labels = ['Soybean', 'Sunflower']
sizes = [percentage_soybean_2009, percentage_sunflower_1996]
colors = ['skyblue', 'yellowgreen']

plt.pie(sizes, labels=labels, colors=colors, autopct='%1.1f%%')
plt.title('Percentage Difference between Soybean and Sunflower Production')
plt.show()

# Creating the bar plot
fig = px.bar(x=['Sunflower vs Soyabean'], y=[percentage_Difference_sunflower_and_soyabean], color=['Entity'])

# Customizing the plot
fig.update_layout(title='Percentage Difference between Sunflower and Soyabean',
                  xaxis_title='Entity',
                  yaxis_title='Percentage Difference')

# Displaying the plot
fig.show()

"""### `Observations:`
>* The maximum Soyabean produced is 3.716936e+08
>* The entity in which maximum Soya Beans production takesplace is: `Namibia`
>* The year in which maximum Soya Beans production took place in Namibia is: `2009`
>* `The Difference in percentage between Sunflower and Soyabean is 17.38225771376428`

### Step 3.4.13| **Lets Explore Rye  Production (tonnes) column**<a id="Step-3.4.13"></a>
"""

df['Rye  Production (tonnes)'].describe()

# Lets check the Entity and Year in which maximum soya bean (tonnes) is produced
Rye_df=df.loc[df['Rye  Production (tonnes)'].idxmax()]
Rye_Entity=Rye_df['Entity']
Rye_Year=Rye_df['Year']
# print the Entity and year in which maximum tea production takes place
print("The entity and year in which maximum Rye production took place are:", Rye_Entity, 'in', Rye_Year)

# Filter the year 2021
df_8=df[df['Year']==2021]
# calculate the soyabean production  in year 2021
Rye_production =df_8['Rye  Production (tonnes)'].sum()
# calculate the Total production
total_Rye_production= df['Rye  Production (tonnes)'].sum()
# percentage of soyabean
percentage_of_Rye_produced_in_2021=(Rye_production/total_Rye_production)*100
# print the soyabean production percentage in 2009
print("The percentage of Rye produced in 2021 is", percentage_of_Rye_produced_in_2021)

# Iterate over each year in the dataset
for year in df['Year'].unique():
    rye_production = df[df['Year'] == year]['Rye  Production (tonnes)'].sum()
    wheat_production = df[df['Year'] == year]['Wheat Production (tonnes)'].sum()

    # Compare rye and wheat production for the current year
    if rye_production > wheat_production:
        print(f"In {year}, rye is produced more than wheat.")
    elif rye_production < wheat_production:
        print(f"In {year}, wheat is produced more than rye.")
    else:
        print(f"In {year}, rye and wheat production are equal.")

"""### `Observations:`
>* The entity in which maximum Rye production took place is: Indonesia
>* The year in which maximum Rye production took place is:  2021
>* The percentage of Rye produced in 2021 is 1.7692564015235082
>* `The Wheat is produced more than Rye Each year`

### Step 3.4.14| **Lets Explore the Potatoes  Production (tonnes) column**<a id="Step-3.4.14"></a>
"""

df['Potatoes  Production (tonnes)'].describe()

# Lets check the Entity and Year in which maximum  is produced
potato_df=df.loc[df['Potatoes  Production (tonnes)'].idxmax()]
potato_Entity=potato_df['Entity']
potato_Year=potato_df['Year']
# print the Entity and year in which maximum tea production takes place
print("The entity and year in which maximum Potatoes  Production (tonnes) took place are:", potato_Entity, 'in', potato_Year)

# Filter the year 2001
df_9=df[df['Year']==2001]
# calculate the soyabean production in year 2001
potato_production =df_9['Potatoes  Production (tonnes)'].sum()
# calculate the Total production
total_potato_production= df['Potatoes  Production (tonnes)'].sum()
# percentage of potato
percentage_of_potato_produced_in_2001=(potato_production/total_potato_production)*100
# print the potato production percentage in 2001
print("The percentage of Potatoes  Production (tonnes) in 2001 is", percentage_of_potato_produced_in_2001)

# Lets see either the Sweet potato or potato is produced in Greater Amount
# Calculate the total production of potatoes and sweet potatoes each year
# Iterate over each year in the dataset
for year in df['Year'].unique():
    potatoes_production = df[df['Year'] == year]['Potatoes  Production (tonnes)'].sum()
    sweet_potatoes_production = df[df['Year'] == year]['Wheat Production (tonnes)'].sum()

    if potatoes_production > sweet_potatoes_production:
        print(f"In {year}, potatoes are produced in greater amount.")
    elif potatoes_production < sweet_potatoes_production:
        print(f"In {year}, sweet potatoes are produced in greater amount.")
    else:
        print(f"In {year}, the production of potatoes and sweet potatoes is equal.")

percentage_Potatoes_2001=2.076773461834241  # specify the percentage of soybean produced in 2009
percentage_Sweet_potato_1994=68.34715521906779  # specify the percentage of sunflower produced in 1996

difference = percentage_of_potato_produced_in_1994 - percentage_Sweet_potato_1994

# Create a pie chart
labels = ['potato', 'Sweetpotato']
sizes = [percentage_soybean_2009, percentage_sunflower_1996]
colors = ['skyblue', 'yellowgreen']

plt.pie(sizes, labels=labels, colors=colors, autopct='%1.1f%%')
plt.title('Percentage Difference between potato and Sweet potato')
plt.show()

"""### `Observations:`
>* The year in which maximum Potatoes  Production (tonnes) took place is: `2001`
>* The entity in which maximum Potatoes  Production (tonnes) takesplace is: `United Arab Emirates`
  >* `The potatoes are produced in greater amount than Sweet potato each year`

### Step 3.4.15| **Lets Explore the Oranges  Production (tonnes) column**<a id="Step-3.4.15"></a>
"""

# Summary statistics of Oranges  Production (tonnes) column
df['Oranges  Production (tonnes)'].describe()

df_oranges=df[['Oranges  Production (tonnes)', 'Entity']]
max_oranges_Entity=df_oranges.loc[df_oranges['Oranges  Production (tonnes)'].idxmax(), 'Entity']
# print the Entity which have maximum oranges production
print("The entity with max Oranges Production is: ", max_oranges_Entity)

df_oranges=df.loc[df['Oranges  Production (tonnes)'].idxmax()]
oranges_Entity=df_oranges['Entity']
oranges_year=df_oranges['Year']
# print the Entity and year in which maximum oranges production took place
print("The entity and year that produced the most Oranges was: ",oranges_Entity,"in", oranges_year)

# Filter the year 1961
df_10=df[df['Year']==1961]
# calculate the production of oranges
oranges_production=df_10['Oranges  Production (tonnes)'].sum()
# total oranges percentage
total_oranges = df['Oranges  Production (tonnes)'].sum()
# calculate the oranges percentage in 1963
oranges_percentage=(oranges_production/total_oranges)*100
# print the oranges percentage in year 1963
print("The orange production percentage in the year 1961 is: ", (oranges_percentage))

"""### `Observations:`
* The year in which maximum peas production took place in United Arab Emirates is: `1983`
  * The maximum Oranges  Production (tonnes) is 7.656665e+07
  * The entity in which maximum Oranges Production takesplace is: `Saudi Arabia`
  * The year in which most Oranges was produced in Saudi Arabia is: `1961`
  * The orange production percentage in the year 1961 is:  1.527749312702053

### Step 3.4.16| **Lets Explore the Peas, dry Production ( tonnes) column**<a id="Step-3.4.16"></a>
"""

df['Peas, dry Production ( tonnes)'].describe()

# Lets check the Entity and Year in which maximum soya bean (tonnes) is produced
peas_df=df.loc[df['Peas, dry Production ( tonnes)'].idxmax()]
peas_Entity=peas_df['Entity']
peas_Year=peas_df['Year']
# print the Entity and year in which maximum tea production takes place
print("The entity and year in which maximum peas, dry Production ( tonnes) production took place are:", peas_Entity, 'in', peas_Year)

# Filter the year 1983
df_11=df[df['Year']==1983]
# calculate the soyabean production  in year 1983
peas_production =df_11['Peas, dry Production ( tonnes)'].sum()
# calculate the Total percentage
total_peas_production= df['Peas, dry Production ( tonnes)'].sum()
# percentage of soyabean
percentage_of_peas_produced_in_1983=(peas_production/total_peas_production)*100
# print the soyabean production percentage in 1983
print("The percentage of peas, dry Production ( tonnes) produced in 1983 is", percentage_of_peas_produced_in_1983)

"""### `Observations:`
* The entity  in which maximum peas, dry Production ( tonnes) takesplace is: `Nepal`
* year in which maximum peas, dry Production ( tonnes) took place is: `1983`
* The percentage of peas, dry Production ( tonnes) in 1983 is 1.4426469401824582
* the maximum peas, dry Production ( tonnes) is 1.663746e+0

### Step 3.4.17| **Lets Explore The Palm oil  Production (tonnes) column**<a id="Step-3.4.17"></a>
"""

df['Palm oil  Production (tonnes)'].describe()

# Lets see which Entity produced more palmoil
df_palmoil=df[['Palm oil  Production (tonnes)', 'Entity']]
max_palmoil_Entity=df_palmoil.loc[df_palmoil['Palm oil  Production (tonnes)'].idxmax(), 'Entity']
# print the Entity which produced Maximum paloil
print("The entity that produced maximum Palm Oil is: ", max_palmoil_Entity)

df_palmoil=df.loc[df['Palm oil  Production (tonnes)'].idxmax()]
palmoil_year=df_palmoil['Year']
palmoil_Entity=df_palmoil['Entity']
# print the Entity and year in which maximum palmoil production took place
print("The entity and year in which the most Palm Oil was produced is: ", palmoil_Entity, 'in', palmoil_year)

# Filter the year 2008
df_12=df[df['Year']==2008]
# calculate the production of palmoil in year 2008
palmoil_production_2008=df_12['Palm oil  Production (tonnes)'].sum()
# Calculate the total palmoil production
total_palmoil_production = df['Palm oil  Production (tonnes)'].sum()
# calculate the percentage of palmoil in year 2008
percentage_palmoil_2008=(palmoil_production_2008/total_palmoil_production)*100
# print the palmoil production percentage in year 2008
print("The percentage of palm oil produced in the year 2008 is: ", percentage_palmoil_2008)

"""### Step 3.4.17.1| **Top Three Countries produced most Palmoil**<a id="Step-3.4.17.1"></a>"""

# Filter relevant columns
columns_to_check = ['Entity', 'Palm oil  Production (tonnes)', 'Sunflower seed  Production (tonnes)']
df_filtered = df[columns_to_check]

# Group the data and calculate total production
grouped_data = df_filtered.groupby('Entity').sum()

# Sort the data in descending order
sorted_data_palm_oil = grouped_data.sort_values(by='Palm oil  Production (tonnes)', ascending=False)
sorted_data_sunflower = grouped_data.sort_values(by='Sunflower seed  Production (tonnes)', ascending=False)

# Select the top three countries
top_three_palm_oil = sorted_data_palm_oil.head(3)
top_three_sunflower = sorted_data_sunflower.head(3)

# Print the results
print("Top three countries producing the most palm oil:")
print(top_three_palm_oil)

print("\nTop three countries producing the most sunflower seeds:")
print(top_three_sunflower)

fig = px.bar(data_frame=df, x='Entity', y='Palm oil  Production (tonnes)', color='Year',
             labels={'Palm oil  Production (tonnes)': 'Palm oil  Production (tonnes)'},
             title="Palmoil Production by Entity")

fig.update_layout(xaxis_title="Entity", yaxis_title="palmoil Production (tonnes)")
fig.show()

sns.histplot(df['Palm oil  Production (tonnes)'])

"""### `Observations:`
* The Entity which produced maximum palmoil is  `Georgia`
  * The year in which maximum palmoil is produced in Georgia is `2008`
  * The percentage of palm oil produced in the year 2008 is:  1.885704617401756
  * The maximum palmoil produced in term of percentage is 7.906779e+07

### Step 3.4.18| **Lets Explore the Grapes  Production (tonnes) column**<a id="Step-3.4.18"></a>
"""

df['Grapes  Production (tonnes)'].describe()

df_Grapes=df.loc[df['Grapes  Production (tonnes)'].idxmax()]
Grapes_year=df_Grapes['Year']
Grapes_Entity=df_Grapes['Entity']
# print the Entity and year in which maximum palmoil production took place
print("The entity and year in which the most Grapes  was produced is: ", Grapes_Entity, 'in', Grapes_year)

# Filter the year 2016
df_13=df[df['Year']==2016]
# calculate the production of Grapes in year 2016
Grapes_production_2016=df_13['Grapes  Production (tonnes)'].sum()
# Calculate the total palmoil production
total_Grapes_production = df['Grapes  Production (tonnes)'].sum()
# calculate the percentage of palmoil in year 2016
percentage_Grapes_2016=(Grapes_production_2016/total_Grapes_production)*100
# print the palmoil production percentage in year 2016
print("The percentage of Grapes produced in the year 2016 is: ", percentage_Grapes_2016)
# Lets calculate the Difference in percentage between the Grapes and oranges produced
Difference_percentage_Grapes_and_Oranges=percentage_Grapes_2016-oranges_percentage
# print the Difference in percentage of Grapes and Oranges produced
print('The Difference in percentage of Grapes and oranges produced',Difference_percentage_Grapes_and_Oranges)

"""### `Observations:`
* The entity in which the most Grapes produced is:  Moldova
* The year in which the most Grapes  was produced is: 2016
* The maximum production of Grapes is 8.001590e+07
* The percentage of Grapes produced in the year 2016 is:  2.0355219827293545
* The Difference in percentage of Grapes and oranges produced 0.5077726700273015

### Step 3.4.19| **Lets Explore the Coffee, green Production ( tonnes) column**<a id="Step-3.4.19"></a>
"""

df['Coffee, green Production ( tonnes)'].describe()

# Lets see the Entity which have maximum production of cofee
df_cofee=df[['Coffee, green Production ( tonnes)', 'Entity']]
max_cofee_Entity=df_cofee.loc[df_cofee['Coffee, green Production ( tonnes)'].idxmax(), 'Entity']
# percentage of cofee
# print the Entity which produced Maximum paloil
print("The entity that produced maximum cofee is: ", max_cofee_Entity)

df_cofee=df.loc[df['Coffee, green Production ( tonnes)'].idxmax()]
cofee_year=df_cofee['Year']
cofee_Entity=df_cofee['Entity']
# print the Entity and year in which maximum cofee is produced
print("The entity that produces maximum coffee per year is: ", cofee_Entity,"in",cofee_year)

# Filter the year 1998
df_14=df[df['Year']==1998]
# Calculate the production of cofee in 1998
coffee_production = df_14['Coffee, green Production ( tonnes)'].sum()
# calculate total production of cofee
cofee_total_production=df['Coffee, green Production ( tonnes)'].sum()
# Lets calculate the production percentage of cofee in 1998
coffee_percentage=(coffee_production/cofee_total_production)*100
# print the cofee percentage
print("The production percentage of coffee in 1998 is: ", coffee_percentage)

sns.histplot(df['Coffee, green Production ( tonnes)'])

"""### `Observations:`
* The entity that produced maximum cofee is:  `Micronesia (country)`
* The year in which maximum cofee is produced in Micronesia (country) is `1998`
* The production percentage of coffee in 1998 is:  2.0053585251363195
* The maximum cofee production is 1.079544e+07

### Step 3.4.20| **Lets Explore the Cocoa beans Production (tonnes) column**<a id="Step-3.4.20"></a>
"""

df['Cocoa beans Production (tonnes)'].describe()

# Lets see the Entity which have maximum production of cofee
df_cocoa=df[['Cocoa beans Production (tonnes)', 'Entity']]
max_cocoa_Entity=df_cocoa.loc[df_cocoa['Cocoa beans Production (tonnes)'].idxmax(), 'Entity']
# percentage of cofee
# print the Entity which produced Maximum paloil
print("The entity that produced maximum cocoa is: ", max_cocoa_Entity)

df_cocoa=df.loc[df['Cocoa beans Production (tonnes)'].idxmax()]
cocoa_year=df_cocoa['Year']
cocoa_Entity=df_cocoa['Entity']
# print the Entity and year in which maximum cofee is produced
print("The entity that produces maximum cocoa per year is: ", cocoa_Entity,"in",cocoa_year)

# Filter the year 1967
df_15=df[df['Year']==1967]
# Calculate the production of cofee in 1967
cocoa_production = df_15['Cocoa beans Production (tonnes)'].sum()
# calculate total production of cofee
cocoa_total_production=df['Cocoa beans Production (tonnes)'].sum()
# Lets calculate the production percentage of cofee in 1967
cocoa_percentage=(cocoa_production/cocoa_total_production)*100
# print the cofee percentage
print("The production percentage of cocoa in 1967 is: ", cocoa_percentage)

# Lets calculate the difference in percentage of coffee and cocoa beans
percentage_Difference_coffee_and_cocoa=coffee_percentage-cocoa_percentage
# print the Difference in percentage
print("The Difference between coffee and cocoa production percentage is ",percentage_Difference_coffee_and_cocoa)

percentage_coffe_1998=2.0053585251363195 # specify the percentage of coffe produced in 2009
percentage_cocoa_1967=1.5036974570480437  # specify the percentage of cocoa produced in 1996

difference = percentage_coffe_1998 - percentage_cocoa_1967

# Create a pie chart
labels = ['coffee', 'cocoa']
sizes = [percentage_coffe_1998, percentage_cocoa_1967]
colors = ['skyblue', 'yellowgreen']

plt.pie(sizes, labels=labels, colors=colors, autopct='%1.1f%%')
plt.title('Percentage Difference between coffee and cocoa')
plt.show()

sns.histplot(df['Cocoa beans Production (tonnes)'])

"""### `Observations:`
* The entity that produced maximum cocoa is:  `Jamaica`
* The year in which Maximum cocoa is produced in jamaica is: `1967`
* The production percentage of coffee in 1967 is:  1.5036974570480437
* The Difference in production percentage between coffee and cocoa is  0.5016610680882758

### Step 3.4.21| **Lets Explore the Meat, chicken  Production (tonnes) column**<a id="Step-3.4.21"></a>
"""

df['Meat, chicken  Production (tonnes)'].describe()

df_meat=df.loc[df['Meat, chicken  Production (tonnes)'].idxmax()]
# lets check which Entity have maximum chicken
meat_Entity=df_meat['Entity']
meat_year=df_meat['Year']
# print the Entity and year which have maximum chicken and meat
print("The entity which have  maximum Chicken and meat is: ",meat_Entity," in", meat_year)

# Filter the year 2021
df_16=df[df['Year']==2021]
# Calculate the production of meat, chicken in 2021
meat_production = df_15['Meat, chicken  Production (tonnes)'].sum()
# calculate total production of cofee
meat_total_production=df['Meat, chicken  Production (tonnes)'].sum()
# Lets calculate the production percentage of cofee in 2021
meat_percentage=(meat_production/meat_total_production)*100
# print the cofee percentage
print("The percentage of meat and chicken in 2021 is: ", meat_percentage)

fig = px.bar(data_frame=df, x='Entity', y='Meat, chicken  Production (tonnes)', color='Year',
             labels={'Meat, chicken  Production (tonnes)': 'Meat, chicken  Production (tonnes)'},
             title="Meat, chicken  Production (tonnes)")

fig.update_layout(xaxis_title="Entity", yaxis_title="Meat Chicken Production (tonnes)")
fig.show()

sns.histplot(df['Meat, chicken  Production (tonnes)'])

"""### `Observations:`
* The entity which have  maximum Chicken and meat is:  `Americas (FAO)`
* The year in which maximum meat and chicken in America (FAO) is: `2021`
* The percentage of meat and chicken in 2021 is:  1.3517783623536095
* The entity in which  maximum banana production takeskplace:  South Korea

### Step 3.4.22| **Lets Explore the Bananas  Production ( tonnes) column**<a id="Step-3.4.22"></a>
"""

df['Bananas  Production ( tonnes)'].describe()

df_banana=df[['Bananas  Production ( tonnes)', 'Entity']]
df_banana_production=df_banana.loc[df_banana['Bananas  Production ( tonnes)'].idxmax(), 'Entity']
# Lets check which entity have maximum Banana production
print(f"The Entity that produce the most bananas is:, {df_banana_production}")

# Filter the dataframe to only include South Korea
df_south_korea = df[df['Entity'] == 'South Korea']

# Get the banana production in South Korea
banana_production_south_korea = df_south_korea['Bananas  Production ( tonnes)'].values[1]

# Get the total banana production worldwide
total_banana_production = df['Bananas  Production ( tonnes)'].sum()

# Calculate the percentage
percentage_banana_production_south_korea = (banana_production_south_korea / total_banana_production) * 100

# Print the result
print(f"The percentage of banana produced in South Korea is: {percentage_banana_production_south_korea}%")

df_banana=df.loc[df['Bananas  Production ( tonnes)'].idxmax()]
# lets check which Entity have maximum chicken
banana_Entity=df_banana['Entity']
banana_year=df_banana['Year']
# print the Entity and year which have maximum banana
print("The entity and year in which  maximum banana production tookplace: ",banana_Entity," in", banana_year)

# Filter the year 1965
df_16=df[df['Year']==1965]
# Calculate the production of banana in 1965
banana_production = df_16['Bananas  Production ( tonnes)'].sum()
# calculate total production of banana
banana_total_production=df['Bananas  Production ( tonnes)'].sum()
# Lets calculate the production percentage of banana in 1965
banana_percentage=(banana_production/banana_total_production)*100
# print the banana percentage
print("The production percentage of banana in 1965 is: ", banana_percentage)

# Diffrence in percentage between Grapes and Bananas
Difference_percentage_Grapes_and_bananas=percentage_Grapes_2016-banana_percentage
# Print the Difference in percentage of Grapes and banana
print('The Difference in percentage of Grapes and Bananas:',Difference_percentage_Grapes_and_bananas)
# Diffrence in percentage between oranges and banana
Difference_percentage_Oranges_and_bananas=banana_percentage-oranges_percentage
# Print the Difference in percentage of oranges and banana
print('The Difference in percentage of Oranges and Bananas:',Difference_percentage_Oranges_and_bananas)

sns.histplot(df['Bananas  Production ( tonnes)'])

"""### `Observations:`
* The entity in which  maximum banana production takeskplace:  South Korea
* The year in which  maximum banana production tookplace in South korea: 1965
* The production percentage of banana in 1965 is:  1.672974937134453
* The Difference in percentage of Grapes and Bananas: 0.36254704559490136
* The Difference in percentage of Oranges and Bananas: 0.14522562443240017

### Step 3.4.23|**Lets Explore the Avocados Production (tonnes) column**<a id="Step-3.4.23"></a>
"""

df['Avocados Production (tonnes)'].describe()

df_Avocadoas=df.loc[df['Avocados Production (tonnes)'].idxmax()]
# lets check which Entity have maximum chicken
Avocadoas_Entity=df_Avocadoas['Entity']
Avocadoas_year=df_Avocadoas['Year']
# print the Entity and year which have maximum banana
print("The entity and year in which  maximum Avocadoas production tookplace: ",Avocadoas_Entity," in", Avocadoas_year)

# Filter the year 1999
df_17=df[df['Year']==1999]
# Calculate the production of banana in 1965
Avocadoas_production = df_17['Avocados Production (tonnes)'].sum()
# calculate total production of banana
Avocadoas_total_production=df['Avocados Production (tonnes)'].sum()
# Lets calculate the production percentage of banana in 1965
Avocadoas_percentage=(Avocadoas_production/Avocadoas_total_production)*100
# print the banana percentage
print("The production percentage of Avocadoas in 1999 is: ", Avocadoas_percentage)

# Diffrence in percentage Between Avocadoas and Oranges
Difference_percentage_Avocadoas_and_Oranges=Avocadoas_percentage-oranges_percentage
# print the Diffrence in percentage Between Avocadoas and Oranges
print('percentage Difference between Avocadoas and Oranges', Difference_percentage_Avocadoas_and_Oranges)
# Diffrence in percentage Between Avocadoas and Grapes
Difference_percentage_Avocadoas_and_Grapes=percentage_Grapes_2016-Avocadoas_percentage
# print the Diffrence in percentage Between Avocadoas and Grapes
print('percentage Difference between Avocadoas and Grapes', Difference_percentage_Avocadoas_and_Grapes)
# print the Diffrence in percentage Between Avocadoas and Bananas
Difference_percentage_Avocadoas_and_bananas=Avocadoas_percentage-banana_percentage
print('percentage Difference between Avocadoas and Bananas', Difference_percentage_Avocadoas_and_bananas)

sns.histplot(df['Avocados Production (tonnes)'])

"""### `Observations:`
* The entity in which  maximum Avocadoas production tookplace:  Libya
* The year in which  maximum Avocadoas production tookplace:1999
* `The production percentage of Avocadoas in 1999 is:  1.7682221375033482`
* `percentage Difference between Avocadoas and Oranges 0.24047282480129528`
* `percentage Difference between Avocadoas and Grapes 0.26729984522600625`
* `percentage Difference between Avocadoas and Bananas 0.09524720036889511`

### Step 3.4.24| **Lets Explore Apples Production (tonnes) column**<a id="Step-3.4.24"></a>
"""

df['Apples Production (tonnes)'].describe()

df_Apples=df[['Apples Production (tonnes)', 'Entity']]
df_Apples_production=df_Apples.loc[df_Apples['Apples Production (tonnes)'].idxmax(), 'Entity']
# Lets check which entity have maximum Banana production
print(f"The Entity that produce the maximum Apples is:, {df_Apples_production}")

df_Apples=df.loc[df['Apples Production (tonnes)'].idxmax()]
# lets check which Entity have maximum chicken
Apples_Entity=df_Apples['Entity']
Apples_year=df_Apples['Year']
# print the Entity and year which have maximum banana
print("The entity and year in which  maximum Apples production tookplace: ",Apples_Entity," in", Apples_year)

# Filter the year 2001
df_18=df[df['Year']==2001]
# Calculate the production of banana in 1965
Apples_production = df_18['Apples Production (tonnes)'].sum()
# calculate total production of banana
Apples_total_production=df['Apples Production (tonnes)'].sum()
# Lets calculate the production percentage of banana in 2001
Apples_percentage=(Apples_production/Apples_total_production)*100
# print the banana percentage
print("The production percentage of Apples in 2001 is: ", Apples_percentage)

# Diffrence in Percentage between Apples and Oranges
Difference_percentage_Apples_and_Oranges=Apples_percentage-oranges_percentage
# Print the Diffrence in Percentage between Apples and Oranges
print('percentage Difference between Apples and Oranges', Difference_percentage_Apples_and_Oranges)
# Diffrence in Percentage between Apples and Grapes
Difference_percentage_Apples_and_Grapes=percentage_Grapes_2016-Apples_percentage
# print the Diffrence in Percentage between Apples and Grapes
print('percentage Difference between Apples and Grapes', Difference_percentage_Apples_and_Grapes)
# Diffrence in Percentage between Apples and Bananas
Difference_percentage_Apples_and_bananas=Apples_percentage-banana_percentage
# Print the Diffrence in Percentage between Apples and Oranges
print('percentage Difference between Apples and Bananas', Difference_percentage_Apples_and_bananas)
# Diffrence in Percentage between Apples and Avocadoas
Difference_percentage_Apples_and_Avocadoas=Apples_percentage-Avocadoas_percentage
# Print the Diffrence in Percentage between Apples and Avocadoas
print('percentage Difference between Apples and Avocadoas', Difference_percentage_Apples_and_Avocadoas)

sns.histplot(df['Apples Production (tonnes)'])

"""### `Observations:`
* The Entity that produce the maximum Apples is:, Morocco
* year in which  maximum Apples production tookplace: `2001`
* The maximum Apples production is 9.314436e+07
* `The production percentage of Apples in 2001 is:  1.8511448127469088`
* `percentage Difference between Apples and Oranges 0.32339550004485584`
* `percentage Difference between Apples and Grapes 0.1843771699824457`
* `percentage Difference between Apples and Bananas 0.17816987561245567`
* `percentage Difference between Apples and Avocadoas 0.08292267524356056`

### Step 3.5| **Global Crop Production Line plot**<a id="Step-3.5"></a>
"""

# Group the data by crop and sum the production values across all years and countries
crop_production = df.drop(['Entity', 'Year'], axis=1).sum()

# Create a line plot to visualize the changes in crop production over the years
plt.figure(figsize=(12, 6))
crop_production.plot(kind='line')
plt.xlabel('Year')
plt.ylabel('Crop Production (tonnes)')
plt.title('Global Crop Production Over the Years')
plt.grid(True)
plt.show()

"""<a id="dealing-with-outliers"></a>
## <span style="font-weight: bold; color: Red; font-size: 35px;">Step 3.6| Dealing with Outliers</span>
"""

numeric_cols=['Year', 'Maize Production (tonnes)',
       'Rice  Production ( tonnes)', 'Yams  Production (tonnes)',
       'Wheat Production (tonnes)', 'Tomatoes Production (tonnes)',
       'Tea  Production ( tonnes )', 'Sweet potatoes  Production (tonnes)',
       'Sunflower seed  Production (tonnes)', 'Sugar cane Production (tonnes)',
       'Soybeans  Production (tonnes)', 'Rye  Production (tonnes)',
       'Potatoes  Production (tonnes)', 'Oranges  Production (tonnes)',
       'Peas, dry Production ( tonnes)', 'Palm oil  Production (tonnes)',
       'Grapes  Production (tonnes)', 'Coffee, green Production ( tonnes)',
       'Cocoa beans Production (tonnes)', 'Meat, chicken  Production (tonnes)',
       'Bananas  Production ( tonnes)', 'Avocados Production (tonnes)',
       'Apples Production (tonnes)']

# List of numeric columns in the dataset
num_cols = [col for col in df.columns if df[col].dtype in ['int64', 'float64']]

# Function to calculate outliers using Z-score
def calculate_zscore_outliers(column):
    z_scores = (column - column.mean()) / column.std()
    return (np.abs(z_scores) > 3).sum() / len(column) * 100

# Dictionary to store outlier percentages for each column
outlier_percentages = {}

# Calculate percentage of outliers for each numeric column
for column in num_cols:
    outlier_percentages[column] = calculate_zscore_outliers(df[column])

# Print the percentage of outliers in each numeric column
for column, percentage in outlier_percentages.items():
    print(f"Column '{column}': {percentage:.2f}% outliers")

plt.figure(figsize=(15,30))
colors=['Red','Green','Blue','Yellow','pink','purple','skyblue','magenta']
num_cols = len(numeric_cols)
rows = (num_cols + 2) // 3  # Calculate the number of rows dynamically

for i, col in enumerate(numeric_cols):
    plt.subplot(rows, 5, i+1)
    sns.boxplot(x=df[col], color=colors[i % len(colors)])  # Reuse colors when it runs out
    plt.title(col)

plt.tight_layout()
plt.show()

# Create boxplots for each numeric column
for i, col in enumerate(numeric_cols):
    # Calculate the quartiles
    q1 = df[col].quantile(0.25)
    q3 = df[col].quantile(0.75)
    iqr = q3 - q1

    # Define the lower and upper bounds for outliers
    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr

    # Remove outliers
    df = df[(df[col] >= lower_bound) & (df[col] <= upper_bound)]

num_cols = [col for col in df.columns if df[col].dtype in ['int64', 'float64']]

# Function to calculate outliers using Z-score
def calculate_zscore_outliers(column):
    z_scores = (column - column.mean()) / column.std()
    return (np.abs(z_scores) > 3).sum() / len(column) * 100

# Dictionary to store outlier percentages for each column
outlier_percentages = {}

# Calculate percentage of outliers for each numeric column
for column in num_cols:
    outlier_percentages[column] = calculate_zscore_outliers(df[column])

# Print the percentage of outliers in each numeric column
for column, percentage in outlier_percentages.items():
    print(f"Column '{column}': {percentage:.2f}% outliers")

plt.figure(figsize=(15,30))
colors=['Red','Green','Blue','Yellow','pink','purple','skyblue','magenta']
num_cols = len(numeric_cols)
rows = (num_cols + 2) // 3  # Calculate the number of rows dynamically

for i, col in enumerate(numeric_cols):
    plt.subplot(rows, 5, i+1)
    sns.boxplot(x=df[col], color=colors[i % len(colors)])  # Reuse colors when it runs out
    plt.title(col)

plt.tight_layout()
plt.show()

""">* I use the Z-score Method is used to Check the Percentage of outliers
>* Then I used IQR Method to Remove Outliers
>* After removing the Outliers I again check the percentage of outliers to identify whether whether outliers are Removed or not
>* Then  I plotted the boxplots to check whether the outliers are present or not

## Step 3.7| **HeatMap**<a id="Step-3.7"></a>
"""

plt.figure(figsize=(20,10))
correlation_matrix=df[['Year', 'Maize Production (tonnes)', 'Rice  Production ( tonnes)', 'Yams  Production (tonnes)',
                                      'Tea  Production ( tonnes )', 'Soybeans  Production (tonnes)', 'Potatoes  Production (tonnes)',
                                      'Peas, dry Production ( tonnes)', 'Palm oil  Production (tonnes)','Meat, chicken  Production (tonnes)',
                                      'Apples Production (tonnes)']].corr()
sns.heatmap(correlation_matrix, annot=True, cbar=False)
plt.title('Correlation Matrix')
plt.xticks(fontsize=12, rotation=45)
plt.yticks(fontsize=12, rotation=0)
plt.show()

"""### Observations:
>* 1 represents the Maximum correlation
>* Negative value Represents very low correlation
>* There is maximum correlation between Peas,dry Production(tonnes) and Apples (0.49) correlation is present between them
>* Then there is maximum correlation between potatoes production (tonnes) and Apples Production (tonnes) (0.41) correlation is present between them
>* Then the correlation is present between the Apples production (tonnes) and year (0.34) correlation is present between them

# `Questions And Answers`

### Q: Identify the Fruit with the highest production globally in the most recent year.
"""

df_Apples=df.loc[df['Apples Production (tonnes)'].idxmax()]
Apples_Entity=df_Apples['Entity']
Apples_year=df_Apples['Year']
print("The entity and year in which maximum Apples production tookplace: ",Apples_Entity," in", Apples_year)

"""### Q: Compare the production of sunflower seeds and soybeans globally.
percentage_Difference_sunflower_and_soyabean=percentage_of_Sunflower_produced_in_1996-percentage_of_soyabean_produced_in_2009
percentage_Difference_sunflower_and_soyabean

### Q: Explore the production trends of cocoa beans and green coffee globally
"""

percentage_coffe_1998=2.0053585251363195 # specify the percentage of coffe produced in 2009
percentage_cocoa_1967=1.5036974570480437 # specify the percentage of cocoa produced in 1996
difference = percentage_coffe_1998 - percentage_cocoa_1967
labels = ['coffee', 'cocoa']
sizes = [percentage_coffe_1998, percentage_cocoa_1967]
colors = ['skyblue', 'yellowgreen']
plt.pie(sizes, labels=labels, colors=colors, autopct='%1.1f%%')
plt.title('Percentage Difference between coffee and cocoa')
plt.show()

"""### Q: Which countries are the top producers for each crop in the most recent year of the dataset?
most_recent_year = df['Year'].max()\
recent_year_df = df[df['Year'] == most_recent_year]\
for column in recent_year_df.columns:\
    if column != 'Entity' and column != 'Year':\
       
"""

# Find the country with the maximum production for the current crop\
top_country = recent_year_df.loc[recent_year_df[column].idxmax(), 'Entity']

# Print the top producer for the current crop
print(f"The top producer for {column} is {top_country}.")

"""### Q: How has the production of each crop changed globally over the years?

"""

crop_production = df.drop(['Entity', 'Year'], axis=1).sum()

#Create a line plot to visualize the changes in crop production over the years
plt.figure(figsize=(12, 6))
crop_production.plot(kind='line')
plt.xlabel('Year')
plt.ylabel('Crop Production (tonnes)')
plt.title('Global Crop Production Over the Years')
plt.grid(True)
plt.show()

"""### Q: How has the global production of chicken meat changed over the years?
fig = px.bar(data_frame=df, x='Entity', y='Meat, chicken  Production (tonnes)', color='Year',
             labels={'Meat, chicken  Production (tonnes)': 'Meat, chicken  Production (tonnes)'},
             title="Meat, chicken  Production (tonnes)")

fig.update_layout(xaxis_title="Entity", yaxis_title="Meat Chicken Production (tonnes)")\
fig.show()

### Q: Analyze the trends in the production of oranges, grapes, and apples over the past decade.
`Difference_percentage_Apples_and_Oranges=Apples_percentage-oranges_percentage`\
print('percentage Difference between Apples and Oranges', Difference_percentage_Apples_and_Oranges)
`Difference_percentage_Apples_and_Grapes=percentage_Grapes_2016-Apples_percentage`\
print('percentage Difference between Apples and Grapes', Difference_percentage_Apples_and_Grapes)

### Q: Identify the top three countries producing the most palm oil and sunflower seeds.
`Filter relevant columns`\
columns_to_check = ['Entity', 'Palm oil  Production (tonnes)', 'Sunflower seed  Production (tonnes)']\
df_filtered = df[columns_to_check]

`Group the data and calculate total production`\
grouped_data = df_filtered.groupby('Entity').sum()

`Sort the data in descending order`\
sorted_data_palm_oil = grouped_data.sort_values(by='Palm oil  Production (tonnes)', ascending=False)\
sorted_data_sunflower = grouped_data.sort_values(by='Sunflower seed  Production (tonnes)', ascending=False)

`Select the top three countries`\
top_three_palm_oil = sorted_data_palm_oil.head(3)\
top_three_sunflower = sorted_data_sunflower.head(3)

`Print the results`\
print("Top three countries producing the most palm oil:")\
print(top_three_palm_oil)

print("\nTop three countrie)

### Q: Which crops, such as maize, rice, and wheat, are considered staple foods globally, and how has their production evolved?
staple_crops = ['Maize Production (tonnes)', 'Rice  Production ( tonnes)', 'Wheat Production (tonnes)']\
staple_data = df[['Year'] + staple_crops]\
staple_data['Year'] = staple_data['Year'].astype(int)\
grouped_data = staple_data.groupby('Year')[staple_crops].sum()\
grouped_data.plot(kind='line')\
plt.xlabel('Year')\
plt.ylabel('Production (tonnes)')\
plt.title('Production Evolution of Maize, Rice, and Wheat')\
plt.legend()\
plt.show()

### **Summary:**
>* `Data Structure and Shape:`
The dataset consists of 'Entity', 'Year', 'Maize Production (tonnes)',
       'Rice  Production ( tonnes)', 'Yams  Production (tonnes)',
       'Wheat Production (tonnes)', 'Tomatoes Production (tonnes)',
       'Tea  Production ( tonnes )', 'Sweet potatoes  Production (tonnes)',
       'Sunflower seed  Production (tonnes)', 'Sugar cane Production (tonnes)',
       'Soybeans  Production (tonnes)', 'Rye  Production (tonnes)',
       'Potatoes  Production (tonnes)', 'Oranges  Production (tonnes)',
       'Peas, dry Production ( tonnes)', 'Palm oil  Production (tonnes)',
       'Grapes  Production (tonnes)', 'Coffee, green Production ( tonnes)',
       'Cocoa beans Production (tonnes)', 'Meat, chicken  Production (tonnes)',
       'Bananas  Production ( tonnes)', 'Avocados Production (tonnes)',
       'Apples Production (tonnes)'columns
        representing food trends across different countries over time.
>* `Data Types:`
The dataset includes variables for [Entity (country), Year, Food items, percentages].
>* `Missing Values:`
No missing values were identified, ensuring data integrity.
>* `Column Analysis:`
Maximum percentages of each food by entity and year were calculated, revealing significant variations in food preferences and consumption patterns.
>* `Outlier Removal:`
Outliers were identified Using Z-score Method and removed using IQR Method to enhance data quality and prevent distortions in analysis.
>* `Correlation Analysis:`
A heatmap was generated to visualize correlations between variables.
"""